//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestCS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModels
    {
        public int Id { get; set; }
        public string ModelName { get; set; }
        public string Color { get; set; }
        public int Year { get; set; }
        public byte CarDoor { get; set; }
        public Nullable<int> Km { get; set; }
        public bool IsUsed { get; set; }
        public int ManifactureId { get; set; }
    
        public virtual Manifactures Manifactures { get; set; }
    }
}
