//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestCS.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CarModels
    {
        public int Id { get; set; }
        
        public string ModelName { get; set; }
        public string Color { get; set; }
        public int Year { get; set; }
        public byte CarDoor { get; set; }
        public Nullable<int> Km { get; set; }
        public bool IsUsed { get; set; }
        public int ManifactureId { get; set; }
    
        public virtual Manifactures Manifactures { get; set; }
    }
}
